// List of all major Pakistani cities
export const PAKISTANI_CITIES = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Gujranwala',
  'Peshawar',
  'Multan',
  'Hyderabad',
  'Islamabad',
  'Quetta',
  'Bahawalpur',
  'Sargodha',
  'Sialkot',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Gujrat',
  'Kasur',
  'Mardan',
  'Dera Ghazi Khan',
  'Sahiwal',
  'Nawabshah',
  'Chiniot',
  'Khanpur',
  'Hafizabad',
  'Kohat',
  'Jacobabad',
  'Shikarpur',
  'Muzaffargarh',
  'Khanewal',
  'Gojra',
  'Mandi Bahauddin',
  'Abbottabad',
  'Dadu',
  'Bahawalnagar',
  'Tando Adam',
  'Khairpur',
  'Pakpattan',
  'Chishtian',
  'Daska',
  'Burewala',
  'Jhelum',
  'Muzaffarabad',
  'Mirpur Khas',
  'Okara',
  'Jaranwala',
  'Chakwal',
  'Sanghar',
  'Kamoke',
  'Nowshera',
  'Kandhkot',
  'Hasilpur',
  'Arifwala',
  'Chakdara',
  'Mian Channun',
  'Bhakkar',
  'Zhob',
  'Jatoi',
  'Haroonabad',
  'Ahmadpur East',
  'Vihari',
  'Kot Addu',
  'Wazirabad',
  'Dera Ismail Khan',
  'Chaman',
  'Kamalia',
  'Umerkot',
  'Tando Allahyar',
  'Kotri',
  'Turbat',
  'Narowal',
  'Shorkot',
  'Chichawatni',
  'Shahdadpur',
  'Moro',
  'Mianwali',
  'Bhalwal',
  'Jamshoro',
  'Pattoki',
  'Renala Khurd',
  'Kot Radha Kishan',
  'Hangu',
  'Kabirwala',
  'Mansehra',
  'Lala Musa',
  'Mailsi',
  'Chunian',
  'Nankana Sahib',
  'Bannu',
  'Pasrur',
  'Timergara',
  'Parachinar',
  'Gwadar',
  'Gilgit',
  'Skardu',
  'Chitral',
  'Murree',
  'Swat',
  'Hunza',
  'Other'
];

// Sort cities alphabetically
export const SORTED_CITIES = [...PAKISTANI_CITIES].sort();

